title: "Sruthi Mathews, PMP"
email: ""
description: "Cybersecurity Notes for the beginner programmer"
baseurl: "" # leave empty for user site
url: "https://ssmaths.github.io"
theme: minima
#author:
#  name: 
#  bio: 
social:
  github: 
  linkedin: sruthimathews
  twitter: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
