title: "Sruthi Mathews, PMP"
email: "https://www.linkedin.com/in/sruthimathews/"
description: "Cybersecurity Notes for the beginner programmer"
baseurl: "" # leave empty for user site
url: "https://ssmaths.github.io"
theme: minima
#author:
  #name: "Your Name"
  #linkedin: your-linkedin-username
  bio: "Project Manager. Learning cybersecurity one ticket at a time."
#social:
  #github: yourusername
  #linkedin: your-linkedin-username
  #twitter: yourtwitter
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
collections:
  projects:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
